// Barrios de la Ciudad Autónoma de Buenos Aires (CABA)
export const CABA_NEIGHBORHOODS = [
  "Agronomía",
  "Almagro",
  "Balvanera",
  "Barracas",
  "Belgrano",
  "Boedo",
  "Caballito",
  "Chacarita",
  "Coghlan",
  "Colegiales",
  "Constitución",
  "Flores",
  "Floresta",
  "La Boca",
  "La Paternal",
  "Liniers",
  "Mataderos",
  "Monte Castro",
  "Monserrat",
  "Nueva Pompeya",
  "Núñez",
  "Palermo",
  "Parque Avellaneda",
  "Parque Chacabuco",
  "Parque Chas",
  "Parque Patricios",
  "Puerto Madero",
  "Recoleta",
  "Retiro",
  "Saavedra",
  "San Cristóbal",
  "San Nicolás",
  "San Telmo",
  "Vélez Sarsfield",
  "Versalles",
  "Villa Crespo",
  "Villa del Parque",
  "Villa Devoto",
  "Villa Gral. Mitre",
  "Villa Lugano",
  "Villa Luro",
  "Villa Ortúzar",
  "Villa Pueyrredón",
  "Villa Real",
  "Villa Riachuelo",
  "Villa Santa Rita",
  "Villa Soldati",
  "Villa Urquiza"
]

// Horarios disponibles para paseos (de 1 hora cada uno)
export const AVAILABLE_HOURS = [
  "07:00", "08:00", "09:00", "10:00", "11:00", "12:00",
  "13:00", "14:00", "15:00", "16:00", "17:00", "18:00",
  "19:00", "20:00", "21:00"
]

// Razas de perros más comunes
export const DOG_BREEDS = [
  "Affenpinscher",
  "Akita",
  "Akita Americano",
  "Alaskan Malamute",
  "American Staffordshire Terrier",
  "Basenji",
  "Basset Hound",
  "Beagle",
  "Bearded Collie",
  "Bichón Frisé",
  "Bichón Maltés",
  "Border Collie",
  "Boston Terrier",
  "Boxer",
  "Braco Alemán",
  "Bulldog Francés",
  "Bulldog Inglés",
  "Bull Terrier",
  "Caniche (Poodle)",
  "Caniche Toy",
  "Cavalier King Charles Spaniel",
  "Chihuahua",
  "Chow Chow",
  "Cocker Spaniel Americano",
  "Cocker Spaniel Inglés",
  "Collie",
  "Corgi Galés de Pembroke",
  "Dálmata",
  "Doberman",
  "Dogo Argentino",
  "Dogo de Burdeos",
  "Fox Terrier",
  "Galgo",
  "Golden Retriever",
  "Gran Danés",
  "Husky Siberiano",
  "Jack Russell Terrier",
  "Labrador Retriever",
  "Lebrel Afgano",
  "Mastín",
  "Mastín Napolitano",
  "Mestizo",
  "Ovejero Alemán (Pastor Alemán)",
  "Ovejero Belga",
  "Pastor Australiano",
  "Pastor de Shetland",
  "Pequinés",
  "Perro de Agua Español",
  "Pinscher Miniatura",
  "Pitbull",
  "Pomerania",
  "Pug (Carlino)",
  "Rottweiler",
  "Samoyedo",
  "San Bernardo",
  "Schnauzer",
  "Schnauzer Miniatura",
  "Shar Pei",
  "Shiba Inu",
  "Shih Tzu",
  "Staffordshire Bull Terrier",
  "Teckel (Dachshund)",
  "Terranova",
  "Terrier Escocés",
  "Vizsla",
  "Weimaraner",
  "West Highland White Terrier",
  "Whippet",
  "Yorkshire Terrier",
  "Otra"
]
